//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SgkAssistant.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string discid {
            get {
                return ((string)(this["discid"]));
            }
            set {
                this["discid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string sgscEnc {
            get {
                return ((string)(this["sgscEnc"]));
            }
            set {
                this["sgscEnc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string lastUserName {
            get {
                return ((string)(this["lastUserName"]));
            }
            set {
                this["lastUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte dbType {
            get {
                return ((byte)(this["dbType"]));
            }
            set {
                this["dbType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("localhost")]
        public string mschostL {
            get {
                return ((string)(this["mschostL"]));
            }
            set {
                this["mschostL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("root")]
        public string mscuidL {
            get {
                return ((string)(this["mscuidL"]));
            }
            set {
                this["mscuidL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LxK190510")]
        public string mscupL {
            get {
                return ((string)(this["mscupL"]));
            }
            set {
                this["mscupL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("asistan")]
        public string mscdbL {
            get {
                return ((string)(this["mscdbL"]));
            }
            set {
                this["mscdbL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3306")]
        public string mscprtL {
            get {
                return ((string)(this["mscprtL"]));
            }
            set {
                this["mscprtL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("K82964397288957")]
        public string solverKey {
            get {
                return ((string)(this["solverKey"]));
            }
            set {
                this["solverKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mysql-1ad3d050-hulusi.b.aivencloud.com")]
        public string mschostR {
            get {
                return ((string)(this["mschostR"]));
            }
            set {
                this["mschostR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("avnadmin")]
        public string mscuidR {
            get {
                return ((string)(this["mscuidR"]));
            }
            set {
                this["mscuidR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LxK+190510.")]
        public string mscupR {
            get {
                return ((string)(this["mscupR"]));
            }
            set {
                this["mscupR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("defaultdb")]
        public string mscdbR {
            get {
                return ((string)(this["mscdbR"]));
            }
            set {
                this["mscdbR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18266")]
        public string mscprtR {
            get {
                return ((string)(this["mscprtR"]));
            }
            set {
                this["mscprtR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gv*6BF37hgPB586esD?hv?_MF&ra@Ps6zzvpCefwxWGQr$DS-bQLZdQpW$8zvxGN")]
        public string cmpCheck {
            get {
                return ((string)(this["cmpCheck"]));
            }
            set {
                this["cmpCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int browser {
            get {
                return ((int)(this["browser"]));
            }
            set {
                this["browser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool disposeDriver {
            get {
                return ((bool)(this["disposeDriver"]));
            }
            set {
                this["disposeDriver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9Pp_A2GN5^fcTQ?*$8^tUGxyPra3WUa7")]
        public string passPhrase {
            get {
                return ((string)(this["passPhrase"]));
            }
            set {
                this["passPhrase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PaleTurquoise")]
        public global::System.Drawing.Color cmmColor {
            get {
                return ((global::System.Drawing.Color)(this["cmmColor"]));
            }
            set {
                this["cmmColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PaleGreen")]
        public global::System.Drawing.Color cmColor {
            get {
                return ((global::System.Drawing.Color)(this["cmColor"]));
            }
            set {
                this["cmColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PaleVioletRed")]
        public global::System.Drawing.Color pdColor {
            get {
                return ((global::System.Drawing.Color)(this["pdColor"]));
            }
            set {
                this["pdColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/html/body/div/table/tbody/tr[4]/td[2]/table[2]/tbody/tr[3]/td/table/tbody/tr[2]/" +
            "td[2]/table")]
        public string tblPD {
            get {
                return ((string)(this["tblPD"]));
            }
            set {
                this["tblPD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/html/body/div/table[1]/tbody/tr[4]/td[2]/table[2]/tbody/tr/td/table/tbody/tr[2]/" +
            "td[2]/table")]
        public string tblET {
            get {
                return ((string)(this["tblET"]));
            }
            set {
                this["tblET"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/html/body/div/table[1]/tbody/tr[4]/td[2]/table[3]/tbody/tr[2]/td[2]/table")]
        public string tblME {
            get {
                return ((string)(this["tblME"]));
            }
            set {
                this["tblME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool autoCaptcha {
            get {
                return ((bool)(this["autoCaptcha"]));
            }
            set {
                this["autoCaptcha"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hideBrowser {
            get {
                return ((bool)(this["hideBrowser"]));
            }
            set {
                this["hideBrowser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Segoe UI")]
        public string rgvFontName {
            get {
                return ((string)(this["rgvFontName"]));
            }
            set {
                this["rgvFontName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8.25")]
        public float rgvFontSize {
            get {
                return ((float)(this["rgvFontSize"]));
            }
            set {
                this["rgvFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public float rgvTitleFontSize {
            get {
                return ((float)(this["rgvTitleFontSize"]));
            }
            set {
                this["rgvTitleFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bold")]
        public global::System.Drawing.FontStyle rgvTitleFontStyle {
            get {
                return ((global::System.Drawing.FontStyle)(this["rgvTitleFontStyle"]));
            }
            set {
                this["rgvTitleFontStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkBlue")]
        public global::System.Drawing.Color rgvTitleFontColor {
            get {
                return ((global::System.Drawing.Color)(this["rgvTitleFontColor"]));
            }
            set {
                this["rgvTitleFontColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/html/body/div/table/tbody/tr[4]/td[2]/table[2]/tbody/tr/td/table/tbody/tr[2]/td[" +
            "2]/table/tbody/tr/td/table")]
        public string tblICR {
            get {
                return ((string)(this["tblICR"]));
            }
            set {
                this["tblICR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//*[@id=\'contentContainer\']/div/table/tbody/tr[2]/td/table/tbody/tr[2]/td[2]/div/" +
            "table[2]")]
        public string tbl6661 {
            get {
                return ((string)(this["tbl6661"]));
            }
            set {
                this["tbl6661"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Segoe UI")]
        public string rgvTitleFontName {
            get {
                return ((string)(this["rgvTitleFontName"]));
            }
            set {
                this["rgvTitleFontName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int cid {
            get {
                return ((int)(this["cid"]));
            }
            set {
                this["cid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int cid2 {
            get {
                return ((int)(this["cid2"]));
            }
            set {
                this["cid2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int sp {
            get {
                return ((int)(this["sp"]));
            }
            set {
                this["sp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int cp {
            get {
                return ((int)(this["cp"]));
            }
            set {
                this["cp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int gun {
            get {
                return ((int)(this["gun"]));
            }
            set {
                this["gun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int gp {
            get {
                return ((int)(this["gp"]));
            }
            set {
                this["gp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int gs {
            get {
                return ((int)(this["gs"]));
            }
            set {
                this["gs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int scd1 {
            get {
                return ((int)(this["scd1"]));
            }
            set {
                this["scd1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int scd2 {
            get {
                return ((int)(this["scd2"]));
            }
            set {
                this["scd2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int scd3 {
            get {
                return ((int)(this["scd3"]));
            }
            set {
                this["scd3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int scd4 {
            get {
                return ((int)(this["scd4"]));
            }
            set {
                this["scd4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int scd5 {
            get {
                return ((int)(this["scd5"]));
            }
            set {
                this["scd5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int sira {
            get {
                return ((int)(this["sira"]));
            }
            set {
                this["sira"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int wait {
            get {
                return ((int)(this["wait"]));
            }
            set {
                this["wait"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("its")]
        public string tblIGL {
            get {
                return ((string)(this["tblIGL"]));
            }
            set {
                this["tblIGL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gradienttable")]
        public string tblHl {
            get {
                return ((string)(this["tblHl"]));
            }
            set {
                this["tblHl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 192, 192")]
        public global::System.Drawing.Color cGunColor {
            get {
                return ((global::System.Drawing.Color)(this["cGunColor"]));
            }
            set {
                this["cGunColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192, 255, 192")]
        public global::System.Drawing.Color gGunColor {
            get {
                return ((global::System.Drawing.Color)(this["gGunColor"]));
            }
            set {
                this["gGunColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SgkAsistan\\PdfTmp")]
        public string hlPdfBasePath {
            get {
                return ((string)(this["hlPdfBasePath"]));
            }
            set {
                this["hlPdfBasePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Desert")]
        public string theme {
            get {
                return ((string)(this["theme"]));
            }
            set {
                this["theme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public byte solverType {
            get {
                return ((byte)(this["solverType"]));
            }
            set {
                this["solverType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color rgvFontColor {
            get {
                return ((global::System.Drawing.Color)(this["rgvFontColor"]));
            }
            set {
                this["rgvFontColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Regular")]
        public global::System.Drawing.FontStyle rgvFontStyle {
            get {
                return ((global::System.Drawing.FontStyle)(this["rgvFontStyle"]));
            }
            set {
                this["rgvFontStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool closeAllBrowsers {
            get {
                return ((bool)(this["closeAllBrowsers"]));
            }
            set {
                this["closeAllBrowsers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string solverKeyIT {
            get {
                return ((string)(this["solverKeyIT"]));
            }
            set {
                this["solverKeyIT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color hlCalisanColor {
            get {
                return ((global::System.Drawing.Color)(this["hlCalisanColor"]));
            }
            set {
                this["hlCalisanColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192, 255, 192")]
        public global::System.Drawing.Color iglGirisColor {
            get {
                return ((global::System.Drawing.Color)(this["iglGirisColor"]));
            }
            set {
                this["iglGirisColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 192, 192")]
        public global::System.Drawing.Color iglCikisColor {
            get {
                return ((global::System.Drawing.Color)(this["iglCikisColor"]));
            }
            set {
                this["iglCikisColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int updateFrequency {
            get {
                return ((int)(this["updateFrequency"]));
            }
            set {
                this["updateFrequency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime lastUpdateCheckDate {
            get {
                return ((global::System.DateTime)(this["lastUpdateCheckDate"]));
            }
            set {
                this["lastUpdateCheckDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Models.Common.TabOrder tabOrderEvizite {
            get {
                return ((global::Models.Common.TabOrder)(this["tabOrderEvizite"]));
            }
            set {
                this["tabOrderEvizite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Models.Common.TabOrder tabOrderLinks {
            get {
                return ((global::Models.Common.TabOrder)(this["tabOrderLinks"]));
            }
            set {
                this["tabOrderLinks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Models.Common.TabOrder tabOrderHesapDurumu {
            get {
                return ((global::Models.Common.TabOrder)(this["tabOrderHesapDurumu"]));
            }
            set {
                this["tabOrderHesapDurumu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Models.Common.TabOrder tabOrderHizmetListe {
            get {
                return ((global::Models.Common.TabOrder)(this["tabOrderHizmetListe"]));
            }
            set {
                this["tabOrderHizmetListe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Models.Common.TabOrder tabOrderIgic {
            get {
                return ((global::Models.Common.TabOrder)(this["tabOrderIgic"]));
            }
            set {
                this["tabOrderIgic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Models.Common.TabOrder tabOrderLastName {
            get {
                return ((global::Models.Common.TabOrder)(this["tabOrderLastName"]));
            }
            set {
                this["tabOrderLastName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Models.Common.TabOrder tabOrderSettings {
            get {
                return ((global::Models.Common.TabOrder)(this["tabOrderSettings"]));
            }
            set {
                this["tabOrderSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Models.Common.TabOrder tabOrderTesvik {
            get {
                return ((global::Models.Common.TabOrder)(this["tabOrderTesvik"]));
            }
            set {
                this["tabOrderTesvik"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Models.Common.TabOrder tabOrderYillik {
            get {
                return ((global::Models.Common.TabOrder)(this["tabOrderYillik"]));
            }
            set {
                this["tabOrderYillik"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AliceBlue")]
        public global::System.Drawing.Color leavePeriodOddColor {
            get {
                return ((global::System.Drawing.Color)(this["leavePeriodOddColor"]));
            }
            set {
                this["leavePeriodOddColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PeachPuff")]
        public global::System.Drawing.Color leavePeriodEvenColor {
            get {
                return ((global::System.Drawing.Color)(this["leavePeriodEvenColor"]));
            }
            set {
                this["leavePeriodEvenColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<Models.Common.PublicHolidays> publicHolidays {
            get {
                return ((global::System.Collections.Generic.List<Models.Common.PublicHolidays>)(this["publicHolidays"]));
            }
            set {
                this["publicHolidays"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime lastLoginDate {
            get {
                return ((global::System.DateTime)(this["lastLoginDate"]));
            }
            set {
                this["lastLoginDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FirstTimeRunningThisVersion {
            get {
                return ((bool)(this["FirstTimeRunningThisVersion"]));
            }
            set {
                this["FirstTimeRunningThisVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LavenderBlush")]
        public global::System.Drawing.Color leavePersonalOddColor {
            get {
                return ((global::System.Drawing.Color)(this["leavePersonalOddColor"]));
            }
            set {
                this["leavePersonalOddColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PowderBlue")]
        public global::System.Drawing.Color leavePersonalEvenColor {
            get {
                return ((global::System.Drawing.Color)(this["leavePersonalEvenColor"]));
            }
            set {
                this["leavePersonalEvenColor"] = value;
            }
        }
    }
}
