@ECHO ON
ECHO Google Chrome, kapatılıyor...
taskkill /IM "chrome.exe" /F
ECHO chromedriver.exe, kapatılıyor...
taskkill /IM "chromedriver.exe" /F
ECHO Firefox, kapatılıyor...
taskkill /IM "firefox.exe" /F
ECHO geckodriver.exe, kapatılıyor...
taskkill /IM "geckodriver.exe" /F
